### ISSUE TITLE
稳定性问题，运行一段时间就会出现导致Crash

### ISSUE THREAD

**Issue by GengHui** [veikai/PyWeChatSpy#1]
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

**Comment by veikai** [comment]
微信版本是不是2.8.0.133呢

**Comment by GengHui** [comment]
微信2.8.0 for Windows 全新发布 2020-01-09  这个版本  方便的话价格微信  我和您沟通一下具体的情况
我微信18021020750

**Comment by veikai** [comment]
已解决
