### ISSUE TITLE
接受好友请求没报错也没反应是什么原因呢

### ISSUE THREAD

**Issue by wuqinggengjueqing** [veikai/PyWeChatSpy#10]
xmlStr = data["content"]
    doc = etree.XML(xmlStr)
    from_wxid = doc.xpath("//msg/@fromusername")[0]
    source_wxid = doc.xpath("//msg/@sourceusername")[0]
    ticket =  doc.xpath("//msg/@ticket")[0]
    encryptusername = doc.xpath("//msg/@encryptusername")[0]
    #print("from_wxid = " + from_wxid + " source_wxid = " + source_wxid + " ticket= " + ticket + " encryptusername =" +encryptusername)
    spy.accept_new_contact(encryptusername, ticket)

**Comment by veikai** [comment]
付费功能
