### ISSUE TITLE
PyWeChatSpy study problems

### ISSUE THREAD

**Issue by 995854654** [veikai/PyWeChatSpy#12]
data["type"]==1怎么才会触发，
我使用了spy.query_login_info()，他就一直循环输出我的信息，怎么才可以暂停

**Comment by veikai** [comment]
query_login_info的返回就是type==1的数据 你这死循环了

**Comment by 995854654** [comment]
大佬，可以说一下query_login_info()怎么用吗，怎么打印自己的信息
spy.query_login_info()
print(f"微信id是{data['wxid']}，名字是{data['nickname']},微信id{data['wechatid']}")
这样打印不出来自己的信息
