### ISSUE TITLE
是否可在Windows服务器上运行？

### ISSUE THREAD

**Issue by yezhiye** [veikai/PyWeChatSpy#29]
在笔记本win10家庭版上是正常使用。在服务器上配置运行example.py后微信正常登录，但是终端不能打印出消息。
操作系统： Windows Server 2019 数据中心版 64位 中文版  跟2016版本
厂商：腾讯云
github下载了今天的代码和教程链接里的微信3.0.0.57。
python:3.8.6 64位
谢谢！

**Comment by veikai** [comment]
服务器上启动代码后多久出现微信登陆窗口

**Comment by yezhiye** [comment]
立即出现，但是终端没有任何信息。

**Comment by veikai** [comment]
看下进程里有没有SpyK.exe 方便的话进群说一下
![CEF16BFF-FCE5-4BC2-BE7F-1ADC037B67E8](https://user-images.githubusercontent.com/24666952/106095477-d43d0e00-616e-11eb-92c4-3cd25538150c.jpeg)

**Comment by yezhiye** [comment]
windows2012版本可用…暂时没有精力配合…还是感谢大佬的工具~
