### ISSUE TITLE
FileNotFoundError: [WinError 2] 系统找不到指定的文件

### ISSUE THREAD

**Issue by wangsheng666** [veikai/PyWeChatSpy#40]
昨天正常运行，今天在
spy = WeChatSpy(response_queue=my_response_queue, key="ab28d8c4768ab3bc2ba86841313f6e32", logger=logger)
报了找不到指定文件，请问是key过期了吗？

**Comment by veikai** [comment]
检查一下SpyK.exe是不是被杀毒误杀了

**Comment by wangsheng666** [comment]
十分感谢，确实是win安全中心的问题，已解决
