### ISSUE TITLE
有效，但是奔溃了，使用方式不对，还是什么？

### ISSUE THREAD

**Issue by q962** [veikai/PyWeChatSpy#5]
使用的是你提供的微信版本  2.8.0，已关闭自动更新

未能保存日志文件。

提示  WeChatSpy.dll 错误

未上报，微信是否真的不上报，上报了，是不是大概率被封号？

- 关闭程序是否 unhook?
- 多次启动关闭会导致什么问题？
- 同时启动多个会导致什么问题？

**Comment by veikai** [comment]
能稳定复现崩溃么？

**Comment by veikai** [comment]
4.2以前的版本在关闭server之后可能会有递归导致的堆栈溢出崩溃 如果版本低可以尝试更新库版本

**Comment by q962** [comment]
> 能稳定复现崩溃么？
无风险吗

用的 4.1，我更新试试

**Comment by veikai** [comment]
4.1是有BUG的 我已经删掉这个包了

**Comment by q962** [comment]
好的，已经用上 4.2 了，看看我不折腾会不会奔溃
